### ISSUE TITLE
Lost ability to reconnect

### ISSUE THREAD

**Issue by mfikes** [annapawlicka/clj-ev3dev#1]
We got up to the point where we were `ssh`d into the device (we are using OS X) and we had to manually give it an address (so the device can't connect to the Internet), and then we added 

```
KexAlgorithms curve25519-sha256 at libssh.org,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group-exchange-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
```

to the bottom of `/etc/ssh/sshd_config`. 

```
root@ev3dev:/etc/ssh# /etc/init.d/ssh restart
[ ok ] Restarting ssh (via systemctl): ssh.service.
```

Then we went through the instructions and got to this one (aside, on the main page it is missing a closing paren).

```clojure
(def infrared-sensor (devices/find-sensor session :infrared "in4"))
```

this resulted in

```
CompilerException com.jcraft.jsch.JSchException: java.net.ConnectException: Connection refused, compiling:(form-init768038103691179243.clj:1:22) 
```

So I exited the shell on the device, and tried to go back in:

```
root@ev3dev:/etc/ssh# exit
logout
Connection to 192.168.2.3 closed.
orion:~ mfikes$ ssh root@192.168.2.3
ssh: connect to host 192.168.2.3 port 22: Connection refused
```

We then rebooted the EV3 and are now getting:

```
orion:~ mfikes$ ssh root@192.168.2.3
ssh_exchange_identification: read: Connection reset by peer
```

Just reporting all of the details.

My hunch is that since it can't connect to `libssh.org`, perhaps the `KexAlgorithms` added to the bottom of `/etc/ssh/sshd_config` caused `ssh` to become unusable.

**Comment by mfikes** [comment]
More detail, FWIW:

```
orion:~ mfikes$ ssh -vvv 192.168.2.3
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to 192.168.2.3 [192.168.2.3] port 22.
debug1: Connection established.
debug3: Incorrect RSA1 identifier
debug3: Could not load "/Users/mfikes/.ssh/id_rsa" as a RSA1 public key
debug1: identity file /Users/mfikes/.ssh/id_rsa type 1
debug1: identity file /Users/mfikes/.ssh/id_rsa-cert type -1
debug1: identity file /Users/mfikes/.ssh/id_dsa type -1
debug1: identity file /Users/mfikes/.ssh/id_dsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.2
ssh_exchange_identification: read: Connection reset by peer
```

**Comment by annapawlicka** [comment]
Typo :( I must have copied the list of `KexAlgorithms` incorrectly (`@` has been replaced with `at`). It should be:

```
KexAlgorithms diffie-hellman-group1-sha1,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
```

**Comment by mfikes** [comment]
Cool. Makes me feel like this was a good bug report :)
I'll try resetting the device. (I assume that involves doing `dd` again.)

**Comment by annapawlicka** [comment]
I wonder if it's possible to change that config on the SD card? Without formatting it. Just plugging it to your Mac and fixing it there.

**Comment by mfikes** [comment]
Right. I tried looking in there and `emacs`ing the files looking for `KexAlgorithms` in the image files there.

```
orion:EV3_BOOT mfikes$ pwd
/Volumes/EV3_BOOT
orion:EV3_BOOT mfikes$ ls -latr
total 11804
-rwxrwxrwx  1 mfikes  staff  3424936 Dec  1 23:22 uInitrd
-rwxrwxrwx  1 mfikes  staff  2589592 Dec  1 23:22 uImage
-rwxrwxrwx  1 mfikes  staff      320 Dec  1 23:22 boot.scr
-rwxrwxrwx  1 mfikes  staff     4096 Feb 18 18:47 ._.Trashes
drwxrwxrwx@ 1 mfikes  staff     2048 Feb 18 18:47 .Trashes
drwxrwxrwt@ 8 root    admin      272 Feb 18 19:56 ..
drwxrwxrwx  1 mfikes  staff     2048 Feb 18 19:57 .fseventsd
drwxrwxrwx@ 1 mfikes  staff    16384 Feb 18 19:58 .
orion:EV3_BOOT mfikes$ 
```

Was worth a try :)  I'll just re-`dd` it.

**Comment by annapawlicka** [comment]
That typo had quite some consequences!

Btw, if you want to your ev3 to have access to internet though that usb cable, you need to enable Internet Sharing in your OSX settings and turn CDC Composite Gadget `on` on the list of ports:

![image](https://cloud.githubusercontent.com/assets/2522010/6260225/6f5bd444-b7d3-11e4-810f-64f2ed471c11.png)

**Comment by mfikes** [comment]
Yep. I bricked a brick :)

**Comment by annapawlicka** [comment]
Let me know if it fixed the issue :)

**Comment by mfikes** [comment]
Confirmed fixed when using `@` from updated `README.md`.

It turns out no Internet access is needed. (Things worked with static non-routable IP between my Mac and device)
